ROBOT-20098 : Added Socker client to execute glusterfs command on Vmexec
CiscoSystems/kadalu pull request #5
Opened 2023-07-06 10:59 UTC by venjetti

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated
- [ ] Add an entry in the `CHANGELOG.md` about the changes.

2023-07-06 12:37 UTC, wdec approved these changes

2023-07-14 06:05 UTC, wdec commented on kadalu_operator/main.py
> +    pv_reclaim_policy = obj["spec"].get("pvReclaimPolicy", "retain")
Why change the default? The less kadalu core changes are done, the better.

2023-07-18 07:38 UTC, wdec requested changes
Guys, this PR needs changes:
1. Revert the changes to the base kadalu py code in terms of the default retention getter return value.
2. SQUASH the commits. We shouldn't have 20 commits!

2023-07-18 07:38 UTC, wdec commented on csi/volumeutils.py
> +    pv_reclaim_policy = storage_data.get("pvReclaimPolicy", "retain")
Why?

2023-07-18 07:39 UTC, venjetti commented on csi/volumeutils.py
> +    pv_reclaim_policy = storage_data.get("pvReclaimPolicy", "retain")
Will do this now.

2023-07-18 07:41 UTC, wdec requested changes

2023-07-18 07:41 UTC, wdec commented on kadalu_operator/main.py
> +    pv_reclaim_policy = obj["spec"].get("pvReclaimPolicy", "retain")
All of these .py changes should be reverted

2023-07-18 07:41 UTC, wdec commented on manifests/kadalu-operator-openshift.yaml
> +                  default: retain
And also revert the ones here for templates that we're not using

2023-07-18 07:41 UTC, wdec commented on csi/volumeutils.py
> +            host += ":24007"
Are you sure about this? An IPv6 address can next to never be extended with a port :X. The IPv6 numeral typically needs to have square braces

2023-07-18 07:43 UTC, venjetti commented on csi/volumeutils.py
> +            host += ":24007"
We reverted this port value that is added previously for ipv6 case. Now we see some errors in ipv6, so testing having this change back.

2023-07-18 07:44 UTC, venjetti commented on manifests/kadalu-operator-openshift.yaml
> +                  default: retain
Will check with Rajesh if these are required and revert these changes. Thanks.

2023-07-18 07:49 UTC, wdec commented on manifests/kadalu-operator-openshift.yaml
> +                  default: retain
These are not needed. We don't use openshift, etc. Revert changes for all the templates we don't use and keep the ones only for the template that we do.

2023-07-18 09:38 UTC, wdec commented on csi/volumeutils.py
> +            host += ":24007"
Reverted where?

2023-07-18 16:36 UTC, closed without merging